[hotfix] formatting fix
variant-inc/terragrunt-variant-apps pull request #83
Opened 2022-05-25 13:57 UTC by rchengvariant

# Description

It looks like a lot of change, but its just formatting + more clarification of lists at the top.
Also made everything lowercase

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

[Buckets](https://github.com/variant-inc/terragrunt-variant-apps/tree/hotfix/s3-dynamodb-sns-sqs-docs/modules/common/buckets)
[DynamoDB](https://github.com/variant-inc/terragrunt-variant-apps/tree/hotfix/s3-dynamodb-sns-sqs-docs/modules/common/dynamodb)
[Message](https://github.com/variant-inc/terragrunt-variant-apps/tree/hotfix/s3-dynamodb-sns-sqs-docs/modules/common/messaging)
[Postgres](https://github.com/variant-inc/terragrunt-variant-apps/tree/hotfix/s3-dynamodb-sns-sqs-docs/modules/common/postgres)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-25 14:34 UTC, vibindaniel commented on modules/common/buckets/README.md
> +#### lifecycle Rule
lifecycle_rule?

2022-05-25 14:35 UTC, vibindaniel commented on modules/common/buckets/README.md
> +##### transition storage class
transition_storage_class

2022-05-25 14:35 UTC, vibindaniel commented on modules/common/buckets/README.md
> +##### noncurrent version transition
same as others above

2022-05-25 17:38 UTC, vibindaniel requested changes

2022-05-25 17:38 UTC, vibindaniel commented on modules/common/buckets/README.md
> +#### lifecycle\_rule
Why did you add \ here?

2022-05-25 20:19 UTC, genghis-tuan commented on modules/common/buckets/README.md
> +#### lifecycle\_rule
I pulled the version from this PR into mkdocs to test and it looks good. i didn't realize the back slashes were for linking either. This looks good in mkdocs so hopefully backstage behaves correctly.

2022-05-25 20:20 UTC, genghis-tuan approved these changes

2022-05-25 20:21 UTC, genghis-tuan commented on modules/common/buckets/README.md
> +#### lifecycle\_rule
I'll resolve this conversation so that we can see in BackStage.

2022-05-26 18:50 UTC, naveen-variant commented on modules/common/dynamodb/README.md
> +| attributes               | list ( object ({ name = string , type = string })) | null            | List of nested attribute definitions.                                                  | [Docs](<[#
Can you fix this link. It is broken.

2022-05-26 18:54 UTC, rchengvariant commented on modules/common/dynamodb/README.md
> +| attributes               | list ( object ({ name = string , type = string })) | null            | List of nested attribute definitions.                                                  | [Docs](<[#
fxied

2022-05-26 19:17 UTC, genghis-tuan requested changes

2022-05-26 19:17 UTC, genghis-tuan commented on modules/common/buckets/README.md
> +| expiration                             | [expiration](#expiration)                                                          | []      | Specifies a period in the object's expire
Just noticed that the example for this is just `Example`. Should it be something else?

2022-05-26 19:17 UTC, genghis-tuan commented on modules/common/buckets/README.md
> +| transition_storage_class               | [transition_storage_class](#transition\_storage\_class)                                | false   | Specifies a period in the object's transitions
Just noticed that the example for this is just `Example`. Should it be something else?

Can this be changed to `Specifies when noncurrent object versions transition` without the last `s'

2022-05-26 19:17 UTC, genghis-tuan commented on modules/common/buckets/README.md
> +| noncurrent_version_transition          | [noncurrent_version_transition](#noncurrent\_version\_transition)                      | false   | Specifies when noncurrent object versions transitions
Just noticed that the example for this is just `Example`. Should it be something else?

Can this be changed to `Specifies when noncurrent object versions transition` without the last `s'

2022-05-26 19:17 UTC, genghis-tuan commented on modules/common/buckets/README.md
> +| noncurrent_version_expiration_days     | [noncurrent_version_expiration_transition](#noncurrent\_version\_expiration\_transition) |         | Specifies when noncurrent object versions transitions
Can this be changed to `Specifies when noncurrent object versions transition` without the last `s'

2022-05-26 19:17 UTC, genghis-tuan commented on modules/common/messaging/README.md
> +| name                              | String |         | This is the human-readable name of the dlq queue                                                                                      | devops
Can this be changed so that the angle brackets are html entities:
`devops-&lt;TOPIC_NAME&gt;\_dlq`

Sorry that I had missed these. They do not show up in Backstage.

2022-05-27 13:29 UTC, genghis-tuan approved these changes
Looks good to me.

2022-05-27 13:38 UTC, merged